services:
  - type: web
    name: n8n
    env: node
    plan: free
    repo: https://github.com/amane421/n8n-render-template
    branch: main
    startCommand: npm run start
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: amane
      - key: N8N_BASIC_AUTH_PASSWORD
        value: amane
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-tzwo.onrender.com
